//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackLab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\BlackJack.mdf;Integr" +
            "ated Security=True")]
        public string BlackJackConnectionString {
            get {
                return ((string)(this["BlackJackConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=\"C:\\USERS\\JOAKIM\\DOCUMENTS\\VISUAL STU" +
            "DIO 2013\\PROJECTS\\BLACKJACKLAB\\BLACKJACKLAB\\BLACKJACK.MDF\";Integrated Security=T" +
            "rue")]
        public string C__USERS_JOAKIM_DOCUMENTS_VISUAL_STUDIO_2013_PROJECTS_BLACKJACKLAB_BLACKJACKLAB_BLACKJACK_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_JOAKIM_DOCUMENTS_VISUAL_STUDIO_2013_PROJECTS_BLACKJACKLAB_BLACKJACKLAB_B" +
                    "LACKJACK_MDFConnectionString"]));
            }
        }
    }
}
