#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackLab
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "BlackJack")]
    public partial class BlackJackDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void InsertSaveState(SaveState instance);
        partial void UpdateSaveState(SaveState instance);
        partial void DeleteSaveState(SaveState instance);
        #endregion

        public BlackJackDataContext() :
            base(global::BlackJackLab.Properties.Settings.Default.BlackJackConnectionString, mappingSource)
        {
            OnCreated();
        }

        public BlackJackDataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BlackJackDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BlackJackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public BlackJackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<SaveState> SaveStates
        {
            get
            {
                return this.GetTable<SaveState>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.SaveState")]
    public partial class SaveState : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private System.Nullable<int> _Cash;

        private System.Nullable<bool> _AI;

        private System.Nullable<int> _BlackJackCount;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnCashChanging(System.Nullable<int> value);
        partial void OnCashChanged();
        partial void OnAIChanging(System.Nullable<bool> value);
        partial void OnAIChanged();
        partial void OnBlackJackCountChanging(System.Nullable<int> value);
        partial void OnBlackJackCountChanged();
        #endregion

        public SaveState()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Cash", AutoSync = AutoSync.Always, DbType = "Int")]
        public System.Nullable<int> Cash
        {
            get
            {
                return this._Cash;
            }
            set
            {
                if ((this._Cash != value))
                {
                    this.OnCashChanging(value);
                    this.SendPropertyChanging();
                    this._Cash = value;
                    this.SendPropertyChanged("Cash");
                    this.OnCashChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AI", DbType = "Bit", IsPrimaryKey = true)]
        public System.Nullable<bool> AI
        {
            get
            {
                return this._AI;
            }
            set
            {
                if ((this._AI != value))
                {
                    this.OnAIChanging(value);
                    this.SendPropertyChanging();
                    this._AI = value;
                    this.SendPropertyChanged("AI");
                    this.OnAIChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BlackJackCount", DbType = "Int")]
        public System.Nullable<int> BlackJackCount
        {
            get
            {
                return this._BlackJackCount;
            }
            set
            {
                if ((this._BlackJackCount != value))
                {
                    this.OnBlackJackCountChanging(value);
                    this.SendPropertyChanging();
                    this._BlackJackCount = value;
                    this.SendPropertyChanged("BlackJackCount");
                    this.OnBlackJackCountChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591